
title: P.D.F.
email: caleb@pdf-institute.com
description: >- 
  P.D.F. is an experimental school that takes the syllabus seriously as a form unto itself.
baseurl: "" 
url: "pdf-institute.com"
author: P.D.F.

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

tagline: P.D.F. is an experimental school based in New York City that takes the syllabus seriously as a form unto itself.
description: P.D.F. is inspired by a living lineage of collaborative study communities where “students are teachers are administrators are staff.” As such, PDF courses are experimental in form and rigorous in content; beyond that, they can be about almost anything. Each course follows a syllabus created by its instructor, and includes a self-published reader co-designed with P.D.F. administrators. Printed in editions equivalent to the size of each class, readers manifest, sustain, and document students’ engagement with the texts—which might include essays, poetry, fiction, artworks, films, performance and more.


collections_dir: contentFolder

collections:
  courses:
    output: true
  about:
    output: true

defaults:
  - scope:
      path: ""
      type: "courses"
    values:
      layout: course
